### ISSUE TITLE
Equipping topaz gear will instantly get disconnected

### ISSUE THREAD

**Issue by shortybsd** [RedBullSlurpie/SlurpiesDongles#2]
When equipping a topaz helmet immediately disconnects a client and gives "Internal Exception: java.io.IOException: An exisitng connection was forcibly closed by the remote host". Every time the player tries to log in they get the same error. Only way to fix this is to delete the player's dat file or modify the inventory of the player's inventory.

Problem is **Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
    at com.rbs.slurpiesdongles.armor.ArmorTopazArmor.onArmorTick(ArmorTopazArmor.java:47) ~[ArmorTopazArmor.class:?]**
Here is the error log from the server when trying to reconnect:
http://pastebin.com/KJQ0iJct

**Comment by RedBullSlurpie** [comment]
Same forge version as last time? Same exact mods as last time? If you updated any mods to a new version, I need to know, thanks. Also, still on a server?

**Comment by RedBullSlurpie** [comment]
Mm, just did some tests, it appears it also happens with my other armor as well. Thank you, I will look further into this.

**Comment by RedBullSlurpie** [comment]
Found the issue, am fixing it as I type to you. I'll post again when I am uploading the new build file.

**Comment by RedBullSlurpie** [comment]
Issue is fixed, and I tested every piece of my armor, and vanilla's. Everything worked fine, so should be all good now until you find another bug. ;P Uploading new build now. Thank you for reporting the bug to me.

**Comment by shortybsd** [comment]
So sorry for the late delay will test immediately. I'll stick with this forge build until a newer stable one comes out. Same mods, updated a few. I made a sh script to list mods and trim .jar off the extension. I'll post mod versions on any newer bug that we may run across. I run a private mod packs with several friends that play. Thank you so much for your fast, hard work. It means a lot.

**Comment by RedBullSlurpie** [comment]
No problem. Download is up, just check the site for the newest version. :) Enjoy.

**Comment by shortybsd** [comment]
Already done brother, implemented and having users connect as we speak or type :P

**Comment by RedBullSlurpie** [comment]
Glad to hear it. May I ask what you are hosting or running?

**Comment by shortybsd** [comment]
Running on a Dell PowerEdge r910 rack server maxed out.. own several. Specs are 2TB ram, (4) 10 core xeon e7-8867l's, 8TB storage on raid 10 and my host is a 1GB connection. I work in IT for a living so hardware is overkill. Run several different game servers e.g. Ark Survival, Space Engineers, Rising World, Wurm Online, Out of Reach, Savage Lands, Unturned and a few more.

**Comment by RedBullSlurpie** [comment]
Haha I've got 1 very similar use it to run most my servers as well, but that is isn't quite the answer I was looking for. I meant for minecraft hehe, got a server for friends, or have a site and stuff and public server?

**Comment by shortybsd** [comment]
hehe sorry about that, it was late and read it incorrectly. I run it for a private group of friends. I've ran some popular servers a while back. We were the largest vanilla Minecraft server when it was first in beta (back in creative only days) called Shorty's World. All my other packs are called Element (something) e.g. ElementCraft, ElementCraft Legendary Elite, ElementCraft United. This current pack is called Element 1.9 (WIP). We have no source of protection mod and I haven't had the time to write our own so public is not an option.
