### ISSUE TITLE
Flight does not work for topaz armor

### ISSUE THREAD

**Issue by IchigoGames** [RedBullSlurpie/SlurpiesDongles#3]
playing on my modpack server and made topaz armor trying to fly with it but nothing happens using Slurpie's Dongles-1.9-3.0.6 will update to the lattes tomorrow so sorry if this is something that has already been fixed.

**Comment by RedBullSlurpie** [comment]
Topaz Armor was working fine for my in all versions of my mod, everything is tested client side, and. It on a server, it could be a possibility that it does not work on the server side. I will have to test tomorrow as I am not home at the moment. Please give me a list of ALL mods you have on the server, and any that you have in your client that aren server side, such as Journeymap or anything similar that is only client side. Please be sure you give me the exact versions of the mods also so I can try to recreate the issue. Also, is there anything in the Server CMD that shows an error when you try to fly with double tapping space bar? I don't know exactly what it would say but it would point to somethint like, com.slurpiesdongles.something.something. (Something is just what I used in place of whatever it's pointing towards) if there is anything in there please copy and paste that into here as well, or you can just upload the server log to Pastebin.com for me. Thank you.

**Comment by RedBullSlurpie** [comment]
I misspelled at the top, I meant to say, and is NOT tested on a server. Only tested client side.

**Comment by RedBullSlurpie** [comment]
Try using the latest version for 1.9, it's 4.0.0. If that doesn't work let me know and I'll take a look at my code tomorrow when I get home.

**Comment by IchigoGames** [comment]
ok i will let you know when i update the pack - server tommrow

**Comment by IchigoGames** [comment]
http://minecraft.curseforge.com/projects/the-new-frontier?gameCategorySlug=modpacks&projectID=243934 shows all the mods in the pack accept for ruins and i also use optfine but other then that it shows everthing also console did not show any msg and i have tested 4.0.0 did not work on server.

**Comment by IchigoGames** [comment]
Fixed not sure why but some one who plays my modpack found out turning theultimate armor flight to false fixed it and now it flys

**Comment by RedBullSlurpie** [comment]
Awesome! Glad to hear it. Hope your enjoying the mod!
