### ISSUE TITLE
{FIXED} Mod interferes with other mod flight

### ISSUE THREAD

**Issue by sironin** [RedBullSlurpie/SlurpiesDongles#4]
This mod disables flight ability for both Baublestuff and Ebon Arts mods, although this mod's flight continues to work.  I'm not sure why that's the case but both these other mods also offer creative flight without interfering with each other.

**Comment by RedBullSlurpie** [comment]
My mod actually doesn't disable flight for other mods. I know the ArmorPlus Mod does. If you have that mod, that mod disables flight for other mods. You can change the config option so that way it doesn't happen. If you aren't using ArmorPlus, then I'm not sure what it could be, but I don't have in the added code that disables flight for other mods.

**Comment by sironin** [comment]
Since you're getting the player entity and doing this, "event.player.capabilities.isFlying = false;" whenever someone isn't wearing your armor, if they have flight from a different mod you're stopping them from flying.  ArmorPlus does it almost exactly the same way, which is why that mod interferes with flight as well.

**Comment by RedBullSlurpie** [comment]
So what are you saying I need to change then? As this isint making sense to me now.

**Comment by sironin** [comment]
I didn't know exactly what needed changing, but I asked the Ebon Arts mod author (his armor flies without conflcit) about what should be done differently in your mod and he explained that you don't need to (and shouldn't) change the flag every player tick.  Just check when armor is equipped and then change the flag then and only then.

**Comment by RedBullSlurpie** [comment]
I'll take a look at it once i have some free time. Thank you for explaining this, it is after all my first mod. :D Thanks again.

**Comment by RedBullSlurpie** [comment]
I've taken a look at it, and am unsure of what to do at the moment, so if you could kindly tell me where to contact the mod author I will do so to see if he can help me out.

**Comment by sironin** [comment]
Here's where I was able to reach him: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2594805-ebon-arts-v2-2-1a-updated-5-7-2016?page=2

I'd guess there's a number of ways to do it.  One might be to only remove flying if a piece is removed rather than the armor just not being present.  Another might be checking flight capability before setting flying to false if they're not wearing your armor (if they're already flying don't change the flags).

**Comment by RedBullSlurpie** [comment]
Until he replies to me or i get somehelp elsewhere, I won't be able to fix it as i am really not sure what to do from here. Thanks for the bug report though.

**Comment by RedBullSlurpie** [comment]
Issue is now fixed this post will be closed. Thank you for your bug report and enjoy the mod! Uploading new build now. :)
